package com.coderslab.entity;
// Generated Sep 16, 2017 5:33:43 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Product generated by hbm2java
 */
@Entity
public class Product implements java.io.Serializable {

    @Id
    private Integer pid;
    private String pname;
    private double price;
    private int qty;

    public Product() {
    }

    public Product(String pname, double price, int qty) {
        this.pname = pname;
        this.price = price;
        this.qty = qty;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getQty() {
        return this.qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    @Override
    public String toString() {
        return "Product{" + "pid=" + pid + ", pname=" + pname + ", price=" + price + ", qty=" + qty + '}';
    }

    

}
